-- The watchdog cannot read `markets`, and says so every six hours.
--
-- It asks one question — what is the newest updated_at — which
-- PostgREST sends as `order=updated_at.desc&limit=1`. With no index on
-- that column Postgres sorts the whole table to answer it, and
-- `markets` is ~190,000 rows, so the statement is cancelled:
--
--   57014 canceling statement due to statement timeout
--
-- scripts/watchdog.mjs reports that as UNREADABLE rather than as a
-- pass, which is correct and is the whole design. But an alarm that
-- fires on every run and can never be cleared is its own defect —
-- this repo has written that lesson down twice already, about a
-- counter that could only be non-zero and about a daily alarm nobody
-- can action. It teaches you to ignore the channel, and the channel is
-- the one that reports a dead recorder on a price path that cannot be
-- backfilled.
--
-- ============================================================
-- RUN THIS ONE. Paste it into the Supabase SQL editor, by itself.
-- ============================================================

create index if not exists markets_updated_at_desc_idx
  on public.markets (updated_at desc nulls last);

-- WHY NOT CONCURRENTLY, WHICH THIS FILE ASKED FOR FIRST.
--
-- CONCURRENTLY cannot run inside a transaction block, and whether the
-- dashboard's SQL editor wraps a lone statement in one is reported
-- both ways — so it is a coin toss that fails with an error looking
-- like the migration is wrong. The plain form always works there.
--
-- The cost of dropping it is a SHARE lock for the duration of the
-- build: WRITES to `markets` wait, reads do not. This index covers a
-- single timestamptz column, so the build is seconds, and `markets` is
-- written by the daily discovery job and by /api/refresh — NOT by
-- either recorder. Nothing being recorded can be lost by this. A
-- refresh call landing mid-build waits and then succeeds.
--
-- Do NOT reach for CONCURRENTLY here on general principle. It exists
-- for builds long enough that blocking writes matters, and it costs a
-- second table pass plus the possibility of leaving an INVALID index
-- behind if the build fails. If you do want it, it needs a direct
-- connection rather than the editor:
--
--   psql "<session-pooler-url>" \
--     -c "create index concurrently if not exists markets_updated_at_desc_idx
--         on public.markets (updated_at desc nulls last);"
--
-- DESC NULLS LAST DOES NOT MATCH A BARE `ORDER BY x DESC`, and this
-- file previously claimed it did. In Postgres, DESC implies NULLS
-- FIRST, so the two orderings differ and the planner cannot use the
-- index to satisfy the sort. Measured after this index was built:
--
--   Sort (top-N heapsort)  Sort Key: updated_at DESC
--     -> Parallel Index Only Scan using markets_updated_at_desc_idx
--        rows=101922 loops=2    Heap Fetches: 47153
--   Execution Time: 1635 ms
--
-- The index WAS used and the query still read ~204,000 entries and
-- sorted them. A Sort node above an index scan is the tell that the
-- ordering does not match.
--
-- THE INDEX IS FINE AND DOES NOT NEED REBUILDING. scripts/watchdog.mjs
-- now asks for `order=updated_at.desc.nullslast`, which matches it, and
-- filters nulls out so the null placement cannot decide the answer.
-- Fixed in the caller rather than here because the other three watched
-- tables rely on plain ascending indexes answering a bare DESC order,
-- and changing this one to match them would only move the mismatch.
--
-- Idempotent: IF NOT EXISTS, so a re-run is a no-op.

-- ============================================================
-- VERIFY. Paste this after, in the same editor.
-- ============================================================
--
-- Should come back in milliseconds, and the plan should say
-- "Index Only Scan Backward" or "Index Scan" — never "Seq Scan".
--
--   explain analyze
--   select updated_at from public.markets order by updated_at desc limit 1;
--
-- And after the next watchdog run, idx_scan should be non-zero:
--
--   select indexrelname, idx_scan, pg_size_pretty(pg_relation_size(indexrelid))
--   from pg_stat_user_indexes
--   where relname = 'markets' and indexrelname = 'markets_updated_at_desc_idx';
